### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KK2-5** [AceHanded/LC-Finnish-Localization-Mod#1]
Hello!

I noticed your repo doesn't have a license. I'd love to create a translation (for a different language) based on your work since it's so organized already. (...I did start my own, but it's just a monolithic "Translations.txt" file where I can't find a single thing!) Could you consider adding a license? Appreciate your consideration!

Best regards.

**Comment by AceHanded** [comment]
Hey!

Apologies for a delayed reply, but I have now added a license to the repository. Good luck with your translation!

-- AceHanded

**Comment by KK2-5** [comment]
Thank you!
