### ISSUE TITLE
New word

### ISSUE THREAD

**Issue by 7AllenWalker7** [AceHanded/LC-Finnish-Localization-Mod#2]
Hello Dear.
I found some text for Items use, like as Set candles, Receiving signal.
also some string for LAN mode:

Local-only
Allow remote connectionsе
Host LAN Server:

And thank you for REGEX, its very good.
Sincerely.

**Comment by AceHanded** [comment]
Hey!

Apologies for a delayed reply, and thank you for bringing these to my attention. I will attempt to resolve these before the next mod update.

-- AceHanded
